name: Fetch upstream
on: 
    schedule:
        - cron: '0 7 * * 1'
    workflow_dispatch:
jobs:
    fetch:
        name: Fetch upstream
        runs-on: ubuntu-latest
        steps:
            - name: Checkout local
              uses: actions/checkout@v3
              with:
                ref: master
                fetch-depth: 0
            - name: Run updater
              run: |
                ./repoupdate.sh