name: Fetch upstream
on: 
    schedule:
        - cron: '0 0 * * 1,4'
    workflow_dispatch:
    push:
      branches: master
jobs:
    fetch:
        name: Fetch upstream
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                ref: master
                fetch-depth: 0
            - name: Run updater
              run: |
                ./repoupdate.sh